## **Top Actor Ratings by Genre**
Identify the top 3 actors with the highest average movie ratings within their most frequent (i.e., top) genre. For each actor, return their name, top genre, and average rating in that genre.


Conditions:<br>
•   If an actor has multiple top genres (same number of appearances), choose the one with the highest average rating.<br>
•   If multiple actors share the same average rating (i.e., a tie in rank), include all tied actors, even if this results in more than 3 total actors. Do not skip rank: if all tied actors share the same rank, the next rank follows sequentially.<br>

DataFrame: top_actors_rating

In [1]:

import pandas as pd

# Create the DataFrame manually with all the data
data = [
    ['Ryan Gosling', 'drama', 9, 'Urban Hunt', '2017-07-03', 'Google'],
    ['Ryan Gosling', 'sci-fi', 8.9, 'Veil of Secrets', '2015-12-23', 'Apple'],
    ['Chris Evans', 'drama', 6.1, 'Crimson Chase', '2017-08-10', 'Apple'],
    ['Meryl Streep', 'drama', 8.2, 'Veil of Secrets', '2019-09-15', 'Google'],
    ['Jennifer Lawrence', 'thriller', 9, 'Whispers in the Wind', '2016-10-15', 'Disney'],
    ['Chris Evans', 'action', 7.1, 'Crimson Chase', '2018-10-10', 'Netflix'],
    ['Ryan Gosling', 'romance', 8.9, 'Frozen Horizon', '2021-10-08', 'Amazon'],
    ['Emma Stone', 'sci-fi', 7.8, 'The Last Stand', '2019-03-31', 'Netflix'],
    ['Denzel Washington', 'action', 9.3, 'Eternal Ember', '2019-01-21', 'Apple'],
    ['Leonardo DiCaprio', 'sci-fi', 6.3, 'Urban Hunt', '2018-03-31', 'Netflix'],
    ['Leonardo DiCaprio', 'drama', 7.5, 'Shadow Realm', '2022-02-16', 'Warner Bros'],
    ['Natalie Portman', 'comedy', 7.5, 'Crimson Chase', '2022-07-08', 'Amazon'],
    ['Ryan Gosling', 'thriller', 9, 'Veil of Secrets', '2023-03-06', 'Google'],
    ['Scarlett Johansson', 'romance', 8.9, 'Veil of Secrets', '2017-06-18', 'Disney'],
    ['Natalie Portman', 'drama', 6.9, 'Breaking the Silence', '2018-07-16', 'Meta'],
    ['Tom Hardy', 'drama', 9, 'Time\'s Edge', '2023-01-19', 'Amazon'],
    ['Leonardo DiCaprio', 'sci-fi', 8, 'Shadow Realm', '2016-08-08', 'Amazon'],
    ['Scarlett Johansson', 'comedy', 9, 'Veil of Secrets', '2017-12-12', 'Disney'],
    ['Meryl Streep', 'romance', 9.6, 'Deep Impact', '2019-01-22', 'Google'],
    ['Scarlett Johansson', 'thriller', 9, 'Breaking the Silence', '2016-03-25', 'Google'],
    ['Scarlett Johansson', 'sci-fi', 8.9, 'Edge of Memory', '2019-04-26', 'Meta'],
    ['Meryl Streep', 'romance', 8.1, 'Veil of Secrets', '2015-02-17', 'Disney'],
    ['Ryan Gosling', 'sci-fi', 9, 'Echoes of War', '2022-03-10', 'Amazon'],
    ['Ryan Gosling', 'action', 9, 'Shadow Realm', '2015-01-14', 'Disney'],
    ['Tom Hardy', 'thriller', 9, 'Bound by Honor', '2016-03-11', 'Warner Bros'],
    ['Tom Hardy', 'sci-fi', 9, 'Crimson Chase', '2016-09-18', 'Amazon'],
    ['Scarlett Johansson', 'thriller', 9, 'Bound by Honor', '2015-01-03', 'Apple'],
    ['Natalie Portman', 'romance', 6.1, 'Frozen Horizon', '2018-06-13', 'Google'],
    ['Emma Stone', 'comedy', 9.5, 'Edge of Memory', '2015-12-17', 'Disney'],
    ['Jennifer Lawrence', 'drama', 9, 'Veil of Secrets', '2016-05-30', 'Google'],
    ['Jennifer Lawrence', 'thriller', 9, 'Bound by Honor', '2021-10-20', 'Meta'],
    ['Leonardo DiCaprio', 'thriller', 9, 'Crimson Chase', '2022-12-30', 'Amazon'],
    ['Chris Evans', 'sci-fi', 8.6, 'Shadow Realm', '2020-10-20', 'Meta'],
    ['Ryan Gosling', 'comedy', 9, 'The Silent Voice', '2015-03-28', 'Apple'],
    ['Denzel Washington', 'comedy', 8.4, 'Whispers in the Wind', '2015-10-18', 'Disney'],
    ['Emma Stone', 'comedy', 6.3, 'Breaking the Silence', '2018-09-15', 'Netflix'],
    ['Denzel Washington', 'comedy', 7.1, 'Chasing Infinity', '2017-05-27', 'Apple'],
    ['Scarlett Johansson', 'sci-fi', 9, 'Time\'s Edge', '2021-06-18', 'Meta'],
    ['Leonardo DiCaprio', 'romance', 9.2, 'Crimson Chase', '2016-01-22', 'Netflix'],
    ['Chris Evans', 'action', 7.7, 'Shadow Realm', '2023-03-06', 'Netflix'],
    ['Ryan Gosling', 'drama', 9, 'The Silent Voice', '2016-03-23', 'Google'],
    ['Leonardo DiCaprio', 'comedy', 8.1, 'Nightfall', '2019-09-25', 'Google'],
    ['Tom Hardy', 'romance', 9, 'Edge of Memory', '2019-12-21', 'Warner Bros'],
    ['Denzel Washington', 'drama', 6.2, 'Veil of Secrets', '2015-03-02', 'Netflix'],
    ['Leonardo DiCaprio', 'comedy', 7.6, 'Chasing Infinity', '2017-05-25', 'Warner Bros'],
    ['Chris Evans', 'drama', 6.7, 'Whispers in the Wind', '2019-05-19', 'Amazon'],
    ['Jennifer Lawrence', 'action', 8.9, 'Veil of Secrets', '2022-06-04', 'Disney'],
    ['Jennifer Lawrence', 'comedy', 9, 'Crimson Chase', '2015-08-28', 'Apple'],
    ['Denzel Washington', 'drama', 9, 'Breaking the Silence', '2015-07-25', 'Apple'],
    ['Jennifer Lawrence', 'thriller', 9, 'Bound by Honor', '2016-10-06', 'Netflix']
]

# Create DataFrame
columns = ['actor_name', 'genre', 'movie_rating', 'movie_title', 'release_date', 'production_company']
top_actors_rating = pd.DataFrame(data, columns=columns)

top_actors_rating.head()

,actor_name,genre,movie_rating,movie_title,release_date,production_company
0,Ryan Gosling,drama,9.0,Urban Hunt,2017-07-03,Google
1,Ryan Gosling,sci-fi,8.9,Veil of Secrets,2015-12-23,Apple
2,Chris Evans,drama,6.1,Crimson Chase,2017-08-10,Apple
3,Meryl Streep,drama,8.2,Veil of Secrets,2019-09-15,Google
4,Jennifer Lawrence,thriller,9.0,Whispers in the Wind,2016-10-15,Disney

In [5]:
# Import your libraries
import pandas as pd

# Start writing code
#top_actors_rating.head()

# More explicit approach showing counts
def get_top_genre_with_rating_tiebreaker(group):
    genre_counts = group.groupby(['genre']).size()
    max_count = genre_counts.max()
    
    tied_genres = genre_counts[genre_counts==max_count].index
    
    if len(tied_genres)==1:
        return tied_genres[0]
        
    else:
        tied_data = group[group['genre'].isin(tied_genres)]
        avg_ratings =tied_data.groupby('genre')['movie_rating'].mean()
        return avg_ratings.idxmax()
        

top_genre_per_actor = top_actors_rating.groupby('actor_name').apply(get_top_genre_with_rating_tiebreaker)
#print(top_genre_per_actor)

# Create DataFrame directly
top_genre_per_actor_df = pd.DataFrame({
    'actor_name': top_genre_per_actor.index,
    'top_genre': top_genre_per_actor.values
})
#print(top_genre_per_actor_df)

top_genre_per_actor_data = top_genre_per_actor_df.merge(top_actors_rating, on='actor_name')
top_genre_per_actor_data = top_genre_per_actor_data[top_genre_per_actor_data['genre'] == top_genre_per_actor_data['top_genre']]

#print(top_genre_per_actor_data)
#top_genre_per_actor_data.drop('top_genre',axis=1,inplace = True)
#print(top_genre_per_actor_data.columns.tolist())

actor_avg_ratings = top_genre_per_actor_data.groupby(['actor_name','genre'])['movie_rating'].mean().reset_index()
actor_avg_ratings.columns = ['actor_name', 'genre', 'average_rating']

actor_avg_ratings = actor_avg_ratings.sort_values('average_rating',ascending=False)
#print(actor_avg_ratings)

actor_avg_ratings['rank'] = actor_avg_ratings['average_rating'].rank(method='dense', ascending=False)
#print(actor_avg_ratings)

top_3_actors = actor_avg_ratings[actor_avg_ratings['rank']<=3]
top_3_actors.drop('rank',axis=1,inplace=True)
top_3_actors.reset_index(drop=True,inplace=True)
top_3_actors

C:\Users\rahit\AppData\Local\Temp\ipykernel_36392\3532055850.py:23: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  top_genre_per_actor = top_actors_rating.groupby('actor_name').apply(get_top_genre_with_rating_tiebreaker)
C:\Users\rahit\AppData\Local\Temp\ipykernel_36392\3532055850.py:50: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  top_3_actors.drop('rank',axis=1,inplace=True)

           actor_name     genre  average_rating
0   Jennifer Lawrence  thriller            9.00
1        Ryan Gosling     drama            9.00
2  Scarlett Johansson  thriller            9.00
3           Tom Hardy     drama            9.00
4        Meryl Streep   romance            8.85
5          Emma Stone    comedy            7.90